In [8]:
import numpy as np
import cvxopt

from mSVM import SVM # See in mSVM.py in detals.
from IPython.display import Latex

In [2]:
data = np.loadtxt('letter-recognition.data', delimiter=',', dtype=str)
print(data.shape)
print(data)
# Extract the class labels (first column) and features (remaining columns)
labels = data[:, 0]
features = data[:, 1:].astype(np.float64)

# Convert class labels to binary: 1 for 'C' and -1 for other letters
binary_labels = np.where(labels == 'C', 1, -1)

# Verify the transformation and separation
binary_labels[:10], features[:5, :]
print(labels)
print(binary_labels)
print(features)

(20000, 17)
[['T' '2' '8' ... '8' '0' '8']
 ['I' '5' '12' ... '8' '4' '10']
 ['D' '4' '11' ... '7' '3' '9']
 ...
 ['T' '6' '9' ... '12' '2' '4']
 ['S' '2' '3' ... '9' '5' '8']
 ['A' '4' '9' ... '7' '2' '8']]
['T' 'I' 'D' ... 'T' 'S' 'A']
[-1 -1 -1 ... -1 -1 -1]
[[ 2.  8.  3. ...  8.  0.  8.]
 [ 5. 12.  3. ...  8.  4. 10.]
 [ 4. 11.  6. ...  7.  3.  9.]
 ...
 [ 6.  9.  6. ... 12.  2.  4.]
 [ 2.  3.  4. ...  9.  5.  8.]
 [ 4.  9.  6. ...  7.  2.  8.]]


<IPython.core.display.Latex object>

In [3]:
train_number = 2000 # size of training data we're going to use
train_labels = binary_labels[0:train_number]
train_data = features[0:train_number]
print(train_data)
print(train_labels)
test_data = features[train_number:]
test_labels = binary_labels[train_number:]

[[ 2.  8.  3. ...  8.  0.  8.]
 [ 5. 12.  3. ...  8.  4. 10.]
 [ 4. 11.  6. ...  7.  3.  9.]
 ...
 [ 4.  8.  4. ... 10.  1.  8.]
 [ 1.  0.  2. ... 10.  0.  8.]
 [ 5. 12.  5. ...  4.  2. 10.]]
[-1 -1 -1 ... -1 -1 -1]


use sigmoid function as kernal function, accuracy is 96.38%

In [26]:
svm_sigmoid = SVM(kernel='sigmoid', C=1.0)

# Train the classifier
svm_sigmoid.fit(train_data, train_labels)

# predictions
y_pred_sigmoid = svm_sigmoid.predict(test_data)

# accuracy
accuracy = np.mean(test_labels == y_pred_sigmoid)
print(f'Accuracy: {accuracy * 100:.2f}%')

     pcost       dcost       gap    pres   dres
 0: -4.6448e+02 -6.2225e+03  3e+04  3e+00  4e-14
 1: -2.6144e+02 -3.2431e+03  4e+03  1e-01  8e-14
 2: -2.4164e+02 -4.2893e+02  2e+02  3e-04  3e-14
 3: -2.4193e+02 -2.4388e+02  2e+00  3e-06  2e-14
 4: -2.4200e+02 -2.4202e+02  2e-02  3e-08  1e-14
 5: -2.4200e+02 -2.4200e+02  2e-04  3e-10  7e-15
Optimal solution found.
Accuracy: 96.38%


use rbf as kernal function, 99.38% correct.

In [30]:
svm_rbf =  SVM(kernel='rbf', C=1.0)

# Train the classifier
svm_rbf.fit(train_data, train_labels)

# predictions
y_pred_rpl = svm_rbf.predict(test_data)

# accuracy
accuracy = np.mean(test_labels == y_pred_rpl)
print(f'Accuracy: {accuracy * 100:.2f}%')

     pcost       dcost       gap    pres   dres
 0: -7.2917e+01 -5.2470e+03  3e+04  2e+00  1e-15
 1: -5.4717e+01 -2.4847e+03  3e+03  1e-01  7e-16
 2: -5.2074e+01 -4.9034e+02  5e+02  2e-02  6e-16
 3: -6.4809e+01 -2.3215e+02  2e+02  5e-03  9e-16
 4: -7.3123e+01 -1.2951e+02  6e+01  5e-04  6e-16
 5: -7.7340e+01 -9.4467e+01  2e+01  2e-05  5e-16
 6: -7.8953e+01 -8.4302e+01  5e+00  5e-15  3e-16
 7: -7.9574e+01 -8.1102e+01  2e+00  4e-15  3e-16
 8: -7.9817e+01 -8.0170e+01  4e-01  5e-15  3e-16
 9: -7.9879e+01 -7.9994e+01  1e-01  6e-15  3e-16
10: -7.9904e+01 -7.9930e+01  3e-02  1e-14  3e-16
11: -7.9909e+01 -7.9917e+01  8e-03  1e-15  3e-16
12: -7.9912e+01 -7.9912e+01  7e-04  7e-15  3e-16
13: -7.9912e+01 -7.9912e+01  2e-05  6e-15  3e-16
Optimal solution found.
Accuracy: 99.32%


linear function, which is 96.86% with a faster speed.

In [7]:
svm_linear =  SVM(kernel='linear', C=1.0)

# Train the classifier
svm_linear.fit(train_data, train_labels)

# predictions
y_pred_linear = svm_linear.predict(test_data)

# accuracy
accuracy = np.mean(test_labels == y_pred_linear)
print(f'Accuracy: {accuracy * 100:.2f}%')

pass1
     pcost       dcost       gap    pres   dres
 0: -2.3870e+02 -4.1945e+03  2e+04  3e+00  7e-12
 1: -1.5629e+02 -2.3022e+03  4e+03  3e-01  5e-12
 2: -1.4022e+02 -1.0296e+03  1e+03  1e-01  4e-12
 3: -1.2683e+02 -8.1853e+02  1e+03  7e-02  3e-12
 4: -1.1416e+02 -5.0515e+02  6e+02  4e-02  3e-12
 5: -1.0447e+02 -3.1601e+02  3e+02  2e-02  3e-12
 6: -9.9498e+01 -2.1483e+02  1e+02  4e-03  3e-12
 7: -1.0318e+02 -1.8607e+02  1e+02  3e-03  3e-12
 8: -1.0351e+02 -1.7148e+02  7e+01  1e-03  3e-12
 9: -1.0408e+02 -1.6833e+02  7e+01  1e-03  3e-12
10: -1.0319e+02 -1.6719e+02  7e+01  9e-04  3e-12
11: -1.0663e+02 -1.5284e+02  5e+01  5e-04  3e-12
12: -1.0678e+02 -1.5182e+02  5e+01  4e-04  3e-12
13: -1.0997e+02 -1.4266e+02  3e+01  2e-04  3e-12
14: -1.0969e+02 -1.4214e+02  3e+01  2e-04  3e-12
15: -1.1231e+02 -1.3638e+02  2e+01  1e-04  3e-12
16: -1.1365e+02 -1.3200e+02  2e+01  7e-05  3e-12
17: -1.1527e+02 -1.2828e+02  1e+01  3e-05  4e-12
18: -1.1625e+02 -1.2580e+02  1e+01  1e-05  4e-12
19: -1.1746e+02